<a href="https://colab.research.google.com/github/AwaisAli37405/Deep_Learning/blob/master/Deep_learning%20with%20Tensorflow%20and%20Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### TensorFlow Tensors

- tensors are multidimensional arrays
- ordered arrangement of numbers
- Tensors could be of zero dimmention only if we have one element (e.g. 1) - 0D
- Tensors could be of one dimmention ([2,0,-1]) - 1D
- or a matrix or a 2D dimmentional matrix

important:

- to create a 1D array we stack up different 0D arrays, similarly to create 2D tensors we stack up multiple 1D arrays.
- Tensors have what we call a shape
- [2,0,-1] 1D tensor has a shape of (3,)
- similarly for a 2D tensor we can have a shape of 4X3. (4,3)
- for a 3D tensor (4,2,3) - 4 2D tensors, each 2D tensor has 2 rows and each row has 1D tensor of 3 cols


In [4]:
# now lets see how tensors can be created using tensor flow
import tensorflow as tf


In [5]:
tensor_zero_d = tf.constant(1)
print(tensor_zero_d)

tf.Tensor(1, shape=(), dtype=int32)


In [6]:
tensor_one_d = tf.constant([1,2,3])
print(tensor_one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [7]:
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
tensor_three_d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [10]:
# similarly:

tensor_three_d.ndim

3

In [11]:
tensor_three_d.shape

TensorShape([2, 2, 3])

In [12]:
# likewise to create a 4D tensor, we will see how many 3D tesors we have, then how many 2D tensors we have and then
# then for every 2D tensors how many we have 1D tensor and then how many cols



# Creating a 4D tensor
tensor_four_d = tf.constant([
    [  # First 3D tensor
        [  # First 2D tensor in the first 3D tensor
            [1, 2, 3],  # First 1D tensor in the first 2D tensor
            [4, 5, 6]   # Second 1D tensor in the first 2D tensor
        ],
        [  # Second 2D tensor in the first 3D tensor
            [7, 8, 9],  # First 1D tensor in the second 2D tensor
            [10, 11, 12] # Second 1D tensor in the second 2D tensor
        ]
    ],
    [  # Second 3D tensor
        [  # First 2D tensor in the second 3D tensor
            [13, 14, 15],  # First 1D tensor in the first 2D tensor
            [16, 17, 18]   # Second 1D tensor in the first 2D tensor
        ],
        [  # Second 2D tensor in the second 3D tensor
            [19, 20, 21],  # First 1D tensor in the second 2D tensor
            [22, 23, 24]   # Second 1D tensor in the second 2D tensor
        ]
    ]
])

# Print the 4D tensor
print(tensor_four_d)





tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)


- when creating the tensors if we have any of the value in float then the type of tensor will be also in float