<a href="https://colab.research.google.com/github/AwaisAli37405/Deep_Learning/blob/master/Deep_learning%20with%20Tensorflow%20and%20Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### TensorFlow Tensors

- tensors are multidimensional arrays
- ordered arrangement of numbers
- Tensors could be of zero dimmention only if we have one element (e.g. 1) - 0D
- Tensors could be of one dimmention ([2,0,-1]) - 1D
- or a matrix or a 2D dimmentional matrix

important:

- to create a 1D array we stack up different 0D arrays, similarly to create 2D tensors we stack up multiple 1D arrays.
- Tensors have what we call a shape
- [2,0,-1] 1D tensor has a shape of (3,)
- similarly for a 2D tensor we can have a shape of 4X3. (4,3)
- for a 3D tensor (4,2,3) - 4 2D tensors, each 2D tensor has 2 rows and each row has 1D tensor of 3 cols


In [1]:
# now lets see how tensors can be created using tensor flow
import tensorflow as tf


In [2]:
tensor_zero_d = tf.constant(1)
print(tensor_zero_d)

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([1,2,3])
print(tensor_one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [4]:
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [6]:
# similarly:

tensor_three_d.ndim

3

In [7]:
tensor_three_d.shape

TensorShape([2, 2, 3])

In [8]:
# likewise to create a 4D tensor, we will see how many 3D tesors we have, then how many 2D tensors we have and then
# then for every 2D tensors how many we have 1D tensor and then how many cols



# Creating a 4D tensor
tensor_four_d = tf.constant([
    [  # First 3D tensor
        [  # First 2D tensor in the first 3D tensor
            [1, 2, 3],  # First 1D tensor in the first 2D tensor
            [4, 5, 6]   # Second 1D tensor in the first 2D tensor
        ],
        [  # Second 2D tensor in the first 3D tensor
            [7, 8, 9],  # First 1D tensor in the second 2D tensor
            [10, 11, 12] # Second 1D tensor in the second 2D tensor
        ]
    ],
    [  # Second 3D tensor
        [  # First 2D tensor in the second 3D tensor
            [13, 14, 15],  # First 1D tensor in the first 2D tensor
            [16, 17, 18]   # Second 1D tensor in the first 2D tensor
        ],
        [  # Second 2D tensor in the second 3D tensor
            [19, 20, 21],  # First 1D tensor in the second 2D tensor
            [22, 23, 24]   # Second 1D tensor in the second 2D tensor
        ]
    ]
])

# Print the 4D tensor
print(tensor_four_d)





tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)


- when creating the tensors if we have any of the value in float then the type of tensor will be also in float

In [9]:
# casting tensor using tensor flow
casted_one_d = tf.cast(tensor_one_d, dtype=tf.float16)
print(tensor_one_d)
print(casted_one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float16)


In [10]:
# converitng to tensors
import numpy as np
numpy_array = np.array([1,2,3])
print(numpy_array)

numpy_tensor = tf.convert_to_tensor(numpy_array)
print(numpy_tensor)




[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [11]:
# creating the identity matrix using tf.eye

identify_matrix = tf.eye(num_rows=5, num_columns=3,batch_shape=[2])
print(identify_matrix)
#

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 5, 3), dtype=float32)


In [12]:
filled_tensor = tf.fill([2,3], 9)
print(filled_tensor)

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [13]:
ones_tensor = tf.ones([2,3])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [14]:
tensor_oneslike = tf.ones_like(tensor_one_d)
print(tensor_oneslike)

tf.Tensor([1 1 1], shape=(3,), dtype=int32)


In [15]:
range_tensor = tf.range(start=1, limit=10, delta=2)
print(range_tensor)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [16]:
# size gives the number of elements
size_tensor = tf.size(range_tensor)
print(size_tensor)

tf.Tensor(5, shape=(), dtype=int32)


In [17]:
print(tf.size(tensor_four_d))

tf.Tensor(24, shape=(), dtype=int32)


In [18]:
tf.random.Generator.from_non_deterministic_state().normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.8992274 , -0.36461154,  0.12102491],
       [-1.0935173 , -3.5754175 ,  1.5185989 ]], dtype=float32)>

In [19]:
tf.random.Generator.from_seed(42).normal(shape=(2,3))# we will get the same random numbers every time we run

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

## Indexing in Tensorflow

In [21]:
tf.range(0,5)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [27]:
tensor_one_d.shape


TensorShape([3])

In [28]:
tensor_one_d[0:1]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [29]:
tensor_two_d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [30]:
tensor_two_d[0,0:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [31]:
tensor_four_d


<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]], dtype=int32)>

In [41]:
tensor_four_d[:, 0, 0, :]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [13, 14, 15]], dtype=int32)>

## Tensorflow Linear algebra Operations